feat: setup husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,18 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-yarn lint:check && yarn prettier:check
+echo "Running lint checks..."
+yarn lint:check
+if [ $? -ne 0 ]; then
+  echo "Lint checks failed."
+  exit 1
+fi
+
+echo "Running Prettier checks..."
+yarn prettier:check
+if [ $? -ne 0 ]; then
+  echo "Prettier checks failed."
+  exit 1
+fi
+
+echo "Pre-commit checks passed."
